import Head from "next/head";
import { BiUserPlus } from "react-icons/bi";
import Table from "../src/components/table";
import Form from "../src/components/form";
import { useState } from "react";

//Crud video youtube*
export default function Iindex() {
  const [visible, setVisible] = useState(false);

  const handler = () => {
    setVisible(!visible);
  };

  return (
    <section>
      <Head>
        <title>Gestion & recrutement </title>
        <meta name="description" content="Generated by vreate next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Gestion du personnel
        </h1>

        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button
              onClick={handler}
              className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800"
            >
              Ajouter un agent{" "}
              <span className="px-1">
                <BiUserPlus size={23}></BiUserPlus>
              </span>
            </button>
          </div>
        </div>

        {/*forme rétractable*/}
        {visible ? <Form></Form> : <></>}

        {/*table*/}
        <div className="container mx-auto">
          <Table></Table>
        </div>
      </main>
    </section>
  );
}
